//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagGardening2014.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaItem
    {
        public MediaItem()
        {
            this.Tags = new HashSet<Tag>();
            this.MediaItemMediaTag = new HashSet<MediaItemMediaTag>();
        }
    
        public int MediaItemId { get; set; }
        public int MediaTypeId { get; set; }
        public int MediaItemStatusId { get; set; }
    
        public virtual MediaType MediaType { get; set; }
        public virtual MediaItemStatus MediaItemStatus { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<MediaItemMediaTag> MediaItemMediaTag { get; set; }
    }
}
