//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagGardening2014.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaType
    {
        public MediaType()
        {
            this.MediaItems = new HashSet<MediaItem>();
        }
    
        public int MediaTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MediaItem> MediaItems { get; set; }
    }
}
