//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagGardening2014.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaItemMediaTag
    {
        public int MediaItemMediaTagId { get; set; }
        public int MediaTagId { get; set; }
        public int MediaItemId { get; set; }
        public string Position { get; set; }
    
        public virtual MediaItem MediaItem { get; set; }
        public virtual MediaTag MediaTag { get; set; }
    }
}
