//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagGardening2014.Web.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tag> TagSet { get; set; }
        public virtual DbSet<MediaItem> MediaItemSet { get; set; }
        public virtual DbSet<MediaItemMediaTag> MediaItemMediaTagSet { get; set; }
        public virtual DbSet<MediaTag> MediaTagSet { get; set; }
        public virtual DbSet<MediaTagType> MediaTagTypeSet { get; set; }
        public virtual DbSet<MediaType> MediaTypeSet { get; set; }
        public virtual DbSet<MediaItemStatus> MediaItemStatusSet { get; set; }
    }
}
